"""
Disease Ontology Parser for the knowledge graph.

Downloads the Disease Ontology OBO file from the official Human Disease Ontology
repository, parses it to extract disease concepts, and filters the results to
the diseases that appear in the local curated slim-terms list AND match the
project disease scope defined in config/project.yaml.

Data Sources:
  - Full DO OBO: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/main/src/ontology/doid.obo
  - Local slim terms: data/raw/diseaseontology/slim-terms.tsv
    (generated by src/generate_disease_slim.py)

Output:
  - slim_terms.tsv: filtered Disease nodes with columns:
      doid, disease_name, definition, umls_cui, symptoms
"""

import logging
import re
from pathlib import Path
from typing import Dict, Optional

import networkx as nx
import pandas as pd

try:
    import obonet
    HAS_OBONET = True
except ImportError:
    HAS_OBONET = False

from .base_parser import BaseParser
from config_loader import get_disease_scope

logger = logging.getLogger(__name__)

# Output name — must match source_filename in ontology_mappings.yaml
OUTPUT_NAME = "slim_terms"

# Pattern to extract "has_symptom <text>" clauses from definition strings
_SYMPTOM_RE = re.compile(r"has[_ ]symptom\s+([^,.\[]+)", re.IGNORECASE)


class DiseaseOntologyParser(BaseParser):
    """
    Parser for the Disease Ontology (DO).

    Extracts disease concepts from the official Disease Ontology OBO file and
    filters them to the intersection of:
      (a) diseases listed in the local curated slim-terms file
          (data/raw/diseaseontology/slim-terms.tsv, generated by
          src/generate_disease_slim.py)
      (b) diseases that match the project disease scope from
          config/project.yaml (primary_terms, umls_cuis, doid_ids, mesh_ids)

    Never downloads from dhimmel/disease-ontology or Hetionet.
    Never hard-codes disease-specific values.
    """

    DO_URL = (
        "https://raw.githubusercontent.com/DiseaseOntology/"
        "HumanDiseaseOntology/main/src/ontology/doid.obo"
    )
    OBO_FILE = "doid.obo"
    SLIM_FILE = "slim-terms.tsv"

    def download_data(self) -> bool:
        """
        Download the Disease Ontology OBO file.

        Returns:
            True if the file is ready; False on failure.
        """
        if not HAS_OBONET:
            logger.error(
                "obonet is not installed. Install it with: pip install obonet"
            )
            return False

        logger.info("Downloading Disease Ontology OBO file...")
        result = self.download_file(self.DO_URL, self.OBO_FILE)
        if not result:
            logger.error("Failed to download Disease Ontology OBO file.")
            return False

        logger.info(f"Disease Ontology OBO ready: {result}")
        return True

    # ------------------------------------------------------------------
    # parse_data
    # ------------------------------------------------------------------

    def parse_data(self) -> Dict[str, pd.DataFrame]:
        """
        Parse the Disease Ontology and return a filtered slim_terms DataFrame.

        Filtering criteria (either must be satisfied):
          (a) DOID appears in the local slim-terms.tsv curated list, OR
          (b) DOID matches the disease scope from config/project.yaml.

        Returns:
            {"slim_terms": DataFrame} with columns:
                doid, disease_name, definition, umls_cui, symptoms
        """
        if not HAS_OBONET:
            logger.error("obonet is required but not installed.")
            return {}

        # ---- (a) Load slim-terms filter set --------------------------------
        slim_doids = self._load_slim_doids()

        # ---- (b) Load disease scope ----------------------------------------
        scope = get_disease_scope()
        scope_doid_ids = set(scope.get("doid_ids", []))
        scope_umls_cuis = set(scope.get("umls_cuis", []))
        scope_mesh_ids = set(scope.get("mesh_ids", []))
        scope_primary_terms = [t.lower() for t in scope.get("primary_terms", [])]

        # ---- Parse OBO file ------------------------------------------------
        obo_path = self.get_file_path(self.OBO_FILE)
        if not Path(obo_path).exists():
            logger.error(f"OBO file not found: {obo_path}")
            return {}

        logger.info(f"Parsing Disease Ontology from {obo_path}")
        try:
            graph = obonet.read_obo(obo_path)
        except Exception as exc:
            logger.error(f"Failed to parse OBO file: {exc}")
            return {}

        doid4_depths = self._compute_doid4_depths(graph)

        rows = []
        for node_id, data in graph.nodes(data=True):
            if not node_id.startswith("DOID:"):
                continue
            if data.get("is_obsolete", False):
                continue

            # ---- Extract xrefs ---------------------------------------------
            xrefs = data.get("xref", [])
            umls_list = [
                x.replace("UMLS_CUI:", "")
                for x in xrefs
                if x.startswith("UMLS_CUI:")
            ]
            mesh_list = [
                x.replace("MESH:", "").replace("MSH:", "")
                for x in xrefs
                if x.startswith("MESH:") or x.startswith("MSH:")
            ]

            # ---- Filter: slim-terms OR disease scope -----------------------
            name = data.get("name", "")
            in_slim = slim_doids is not None and node_id in slim_doids
            matches_scope = self._matches_scope(
                node_id,
                name,
                umls_list,
                mesh_list,
                scope_doid_ids,
                scope_umls_cuis,
                scope_mesh_ids,
                scope_primary_terms,
            )
            if not (in_slim or matches_scope):
                continue

            # ---- Filter: Skip overly broad categorical nodes -----------------------
            # Exclude terms whose EVERY parent is a direct child of DOID:4
            # (depth ≤ 1). Terms with at least one deep parent (depth ≥ 2)
            # are specific enough to keep.
            is_a_list = [
                entry.split(" !")[0].strip()
                for entry in data.get("is_a", [])
            ]
            if self._is_too_broad(is_a_list, doid4_depths):
                if in_slim:
                    logger.debug(
                        "Excluded broad slim term: %s (%s)", node_id, name
                    )
                continue

            # ---- Extract fields --------------------------------------------
            raw_def = data.get("def", "")
            definition = self._clean_definition(raw_def)
            umls_cui = "|".join(umls_list) if umls_list else ""
            symptoms = self._extract_symptoms(raw_def)

            rows.append(
                {
                    "doid": node_id,
                    "disease_name": name,
                    "definition": definition,
                    "umls_cui": umls_cui,
                    "symptoms": symptoms,
                }
            )

        if not rows:
            logger.warning(
                "No Disease Ontology terms passed both filters. "
                "Check slim-terms.tsv and config/project.yaml disease_scope."
            )

        df = pd.DataFrame(
            rows,
            columns=["doid", "disease_name", "definition", "umls_cui", "symptoms"],
        )
        df["source_database"] = "Disease Ontology"
        logger.info(f"Disease Ontology slim_terms: {len(df)} rows")
        return {OUTPUT_NAME: df}

    # ------------------------------------------------------------------
    # get_schema
    # ------------------------------------------------------------------

    def get_schema(self) -> Dict[str, Dict[str, str]]:
        return {
            OUTPUT_NAME: {
                "doid": "Disease Ontology ID (e.g., DOID:10652)",
                "disease_name": "Common disease name",
                "definition": "Disease definition/description from DO",
                "umls_cui": "UMLS CUI cross-reference(s), pipe-separated if multiple",
                "symptoms": (
                    "Pipe-separated symptom terms extracted from the DO definition"
                ),
            }
        }

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _compute_doid4_depths(graph) -> dict:
        """Return {node_id: min_depth_from_DOID:4} via NetworkX BFS.

        obonet edges run child→parent, so reverse the graph to traverse
        downward from the root.
        """
        return dict(
            nx.single_source_shortest_path_length(graph.reverse(), "DOID:4")
        )

    @staticmethod
    def _is_too_broad(is_a_list: list, depth_map: dict) -> bool:
        """
        Return True if every direct parent of a term is depth ≤ 1 from DOID:4.

        Such terms are pure categorical nodes (e.g. "monogenic disease" whose
        only parent is "genetic disease" at depth 1). Terms with at least one
        parent at depth ≥ 2 are specific enough to pass.
        """
        if not is_a_list:
            return False
        return all(depth_map.get(p, 999) <= 1 for p in is_a_list)

    def _load_slim_doids(self) -> Optional[set]:
        """
        Load the set of DOIDs from the local slim-terms.tsv.

        Returns the set of DOID strings, or None if the file is absent
        (in which case the slim filter is skipped with a warning).
        """
        slim_path = Path(self.get_file_path(self.SLIM_FILE))
        if not slim_path.exists():
            logger.warning(
                f"slim-terms.tsv not found at {slim_path}. "
                "Run `python src/generate_disease_slim.py` to generate it. "
                "Proceeding without slim-terms filter."
            )
            return None

        try:
            df = pd.read_csv(slim_path, sep="\t", dtype=str)
            doids = set(df["doid"].dropna().tolist())
            logger.info(f"Loaded {len(doids)} DOIDs from slim-terms.tsv")
            return doids
        except Exception as exc:
            logger.error(f"Failed to read slim-terms.tsv: {exc}")
            return None

    @staticmethod
    def _matches_scope(
        node_id: str,
        name: str,
        umls_list: list,
        mesh_list: list,
        scope_doid_ids: set,
        scope_umls_cuis: set,
        scope_mesh_ids: set,
        scope_primary_terms: list,
    ) -> bool:
        """Return True if the disease matches any disease-scope criterion."""
        # If no scope is configured, accept all diseases
        if not any(
            [scope_doid_ids, scope_umls_cuis, scope_mesh_ids, scope_primary_terms]
        ):
            return True
        if node_id in scope_doid_ids:
            return True
        if any(cui in scope_umls_cuis for cui in umls_list):
            return True
        if any(mid in scope_mesh_ids for mid in mesh_list):
            return True
        name_lower = name.lower()
        if any(term in name_lower for term in scope_primary_terms):
            return True
        return False

    @staticmethod
    def _clean_definition(raw_def: str) -> str:
        """
        Strip OBO-format quotes and trailing database cross-reference brackets
        from a definition string.

        OBO def format: '"text." [url:..., url:...]'
        Step 1: strip leading quote  → 'text." [url:...]'
        Step 2: remove trailing [..] → 'text."'
        Step 3: strip trailing quote → 'text.'
        """
        if not raw_def:
            return ""
        definition = raw_def.strip()
        # Step 1: remove leading quote
        if definition.startswith('"'):
            definition = definition[1:]
        # Step 2: remove trailing [reference] block (last occurrence of " [")
        bracket_idx = definition.rfind(" [")
        if bracket_idx != -1:
            definition = definition[:bracket_idx]
        # Step 3: remove trailing quote left from OBO "text" [refs] format
        definition = definition.rstrip('"').strip()
        return definition

    @staticmethod
    def _extract_symptoms(raw_def: str) -> str:
        """
        Extract symptom names from a DO definition string.

        DO definitions embed symptoms as:
          "... has_symptom fever, has_symptom arthralgia ..."
        or
          "... has symptom fever ..."

        Returns a pipe-separated string of symptom terms, or "" if none found.
        """
        if not raw_def:
            return ""
        matches = _SYMPTOM_RE.findall(raw_def)
        symptoms = [m.strip().rstrip(",;.") for m in matches if m.strip()]
        return "|".join(symptoms) if symptoms else ""
